### ISSUE TITLE
Add linear updating method to SimulatedAnnealing.autofit

### ISSUE THREAD

**Issue by leonlan** [N-Wouda/ALNS#117]
`SimulatedAnnealing.autofit` assumes that the final temperature always goes to 1:

https://github.com/N-Wouda/ALNS/blob/8ef4665c9cb27923497e11dccf3e75d9b58821bd/alns/accept/SimulatedAnnealing.py#L104-L128

It would be nice to have an `end_worse` argument for simulated annealing, so that we can have final temperatures other than 1. The current `worse` parameter could rephrased to `start_worse`. 
- Issue: I don't know if there is a good default value for `start_worse` to make this a non-breaking change

It would also be nice to have an `method` argument to choose which updating method should be used. The current implementation assumes exponential updating. This is definitely not breaking.

For reference, RRT already has the two above features:
https://github.com/N-Wouda/ALNS/blob/8ef4665c9cb27923497e11dccf3e75d9b58821bd/alns/accept/RecordToRecordTravel.py#L109-L167

**Comment by N-Wouda** [comment]
> It would be nice to have an `end_worse` argument for simulated annealing, so that we can have final temperatures other than 1. The current `worse` parameter could rephrased to `start_worse`.

What we have right now is, for better or worse, something that's done in the literature in almost precisely this way, using the current phrasing. I don't see an obvious way to make this change in a non-breaking way. Since it's used, and we cannot change this without requiring another version bump, I'm leaning wontfix on this one.

> It would also be nice to have an `method` argument to choose which updating method should be used.

That's fine by me. We can just add this as a new argument. The math for the linear case is even easier than what we have now, so this should work out fine.

**Comment by leonlan** [comment]
> What we have right now is, for better or worse, something that's done in the literature in almost precisely this way, using the current phrasing. I don't see an obvious way to make this change in a non-breaking way. Since it's used, and we cannot change this without requiring another major version bump, I'm leaning wontfix on this one.

I agree. Let's just add the linear updating method.
