### ISSUE TITLE
"State of the Field" section in JOSS paper

### ISSUE THREAD

**Issue by N-Wouda** [N-Wouda/ALNS#129]
From the review in https://github.com/openjournals/joss-reviews/issues/5028:

>State of the field: Do the authors describe how this software compares to other commonly-used packages?

And reviewer comment:

>See the JOSS required item above to please add "State of the Field" to cover how this package compares to other packages. If none such exists (which I doubt it, since stochastic local search is well-known), please make the contribution explicit. If there are other tools, please cover mainstream ones, if any and mention where each would benefit the most (e.g., genetic algorithms for multi-point solutions vs. alns)

There's some references already written down in the review that might be useful. I'm thinking ten-or-so references at most (incl. some open source Python/other optimization packages), and text similar in size to the statement of need.

@leonlan can you have a go at this?

**Comment by leonlan** [comment]
Sure thing. Will work on this tomorrow!

**Comment by leonlan** [comment]
Packages (mostly Python)
- https://github.com/DEAP/deap
- https://github.com/jMetal/jMetalPy
- https://github.com/jmejia8/Metaheuristics.jl
- https://github.com/ac-tuwien/pymhlib
  - See https://github.com/ac-tuwien/pymhlib/blob/master/pymhlib/alns.py for alns
- https://github.com/thieu1995/mealpy
- https://github.com/ljvmiranda921/pyswarms
- https://github.com/anyoptimization/pymoo
- https://github.com/nojhan/paradiseo

Not a package but relevant
- https://github.com/alberto-santini/adaptive-large-neighbourhood-search

**Comment by leonlan** [comment]
I think the list above includes the most relevant packages. 

In this [branch](https://github.com/N-Wouda/ALNS/compare/joss-paper...state-of-the-field), I slightly modified the text in the "statement of need" and added a single line of text to refer to other libraries. This is what many JOSS papers seem to do as well, and IMO it feels enough.

It feels a bit of a stretch to write a section on "State of the Field", because none of these packages are completely dedicated to single trajectory and single objective algorithms. But I think I can also make an attempt to write this.

I'll have a better look at this tomorrow, I need to fix my jetlag :-)
